name-template: Upcoming Changes
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Upcoming Changes

  $CHANGES
